version: "3.8"

services:
  tensorflow-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    runtime: nvidia
    container_name: tensorflow_titanic
    volumes:
      - .:/app
    ports:
      - "8888:8888" # Expose Jupyter or any other ports if needed
    environment:
      - ENV=development
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: poetry run python kaggle_titanic/titanic__tensorflow_2.py
